name: qr
description: "Personel Takip Uygulaması"

publish_to: 'none'

version: 6.0.0+6

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  dio: ^5.3.3
  flutter_secure_storage: ^9.0.0
  connectivity_plus: ^4.0.2
  internet_connection_checker: ^1.0.0+1
  flutter_barcode_scanner: ^2.0.0
  permission_handler: ^10.2.0
  pin_code_text_field: ^1.8.0
  intl: ^0.18.1
  geolocator: ^10.1.0
  flutter_masked_text2: ^0.9.1
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  flutter_svg: ^2.0.9
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.6
  flutter_local_notifications: ^16.2.0
  url_launcher: ^6.2.4
  new_version_plus: ^0.0.11
  syncfusion_flutter_charts: ^24.2.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: lib/Assets/Fonts/Inter/Inter-Regular.ttf
        - asset: lib/Assets/Fonts/Inter/Inter-Bold.ttf

  assets:
    - lib/Assets/Images/
    - lib/Assets/Icons/
